"""Shared constants for websearch mixins."""

from __future__ import annotations

AUTHORITATIVE_ALLOWLIST = {
    "reuters.com",
    "bloomberg.com",
    "wsj.com",
    "ft.com",
    "cnbc.com",
    "barrons.com",
    "marketwatch.com",
    "sec.gov",
    "federalreserve.gov",
    "ecb.europa.eu",
    "bankofengland.co.uk",
    "bis.org",
    "imf.org",
    "worldbank.org",
    "oecd.org",
    "bls.gov",
    "bea.gov",
    "treasury.gov",
    "nasdaq.com",
    "nyse.com",
    "cboe.com",
    "ice.com",
    "cmegroup.com",
    "spglobal.com",
    "moodys.com",
    "fitchratings.com",
    "finra.org",
    "investing.com",
    "fxstreet.com",
    "coindesk.com",
    "cointelegraph.com",
    "theblock.co",
    "ic3.gov",
    "dataplus.sec.gov",
    "edgar.sec.gov",
}

SOURCE_REGISTRY = [
    {
        "name": "Reuters",
        "domain": "reuters.com",
        "fetch_mode": "rss",
        "coverage": 1.0,
        "reliability": 1.0,
        "relevance": 0.95,
        "efficiency": 0.95,
        "crawl_url": "https://www.reuters.com/world/",
    },
    {
        "name": "Bloomberg",
        "domain": "bloomberg.com",
        "fetch_mode": "rss",
        "coverage": 0.98,
        "reliability": 0.98,
        "relevance": 0.93,
        "efficiency": 0.9,
        "crawl_url": "https://www.bloomberg.com/markets",
    },
    {
        "name": "WSJ",
        "domain": "wsj.com",
        "fetch_mode": "rss",
        "coverage": 0.92,
        "reliability": 0.97,
        "relevance": 0.9,
        "efficiency": 0.88,
        "crawl_url": "https://www.wsj.com/news/markets",
    },
    {
        "name": "Financial Times",
        "domain": "ft.com",
        "fetch_mode": "rss",
        "coverage": 0.9,
        "reliability": 0.97,
        "relevance": 0.89,
        "efficiency": 0.88,
        "crawl_url": "https://www.ft.com/markets",
    },
    {
        "name": "CNBC",
        "domain": "cnbc.com",
        "fetch_mode": "rss",
        "coverage": 0.89,
        "reliability": 0.92,
        "relevance": 0.9,
        "efficiency": 0.91,
        "crawl_url": "https://www.cnbc.com/world/?region=world",
    },
    {
        "name": "SEC",
        "domain": "sec.gov",
        "fetch_mode": "api",
        "coverage": 0.72,
        "reliability": 1.0,
        "relevance": 0.85,
        "efficiency": 0.83,
    },
    {
        "name": "Federal Reserve",
        "domain": "federalreserve.gov",
        "fetch_mode": "api",
        "coverage": 0.7,
        "reliability": 1.0,
        "relevance": 0.83,
        "efficiency": 0.82,
    },
    {
        "name": "BLS",
        "domain": "bls.gov",
        "fetch_mode": "api",
        "coverage": 0.66,
        "reliability": 1.0,
        "relevance": 0.8,
        "efficiency": 0.81,
    },
    {
        "name": "CoinDesk",
        "domain": "coindesk.com",
        "fetch_mode": "rss",
        "coverage": 0.76,
        "reliability": 0.9,
        "relevance": 0.86,
        "efficiency": 0.9,
    },
    {
        "name": "The Block",
        "domain": "theblock.co",
        "fetch_mode": "playwright",
        "coverage": 0.72,
        "reliability": 0.89,
        "relevance": 0.84,
        "efficiency": 0.6,
    },
]
